// Command api-surface writes a deterministic manifest of Hermes' public Go API.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/importer"
	"go/token"
	"go/types"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

var publicPackages = []string{
	"github.com/sidwiskers/hermes",
	"github.com/sidwiskers/hermes/api",
	"github.com/sidwiskers/hermes/dedupe",
	"github.com/sidwiskers/hermes/framework",
	"github.com/sidwiskers/hermes/fsm",
	"github.com/sidwiskers/hermes/observe",
	"github.com/sidwiskers/hermes/ratelimit",
	"github.com/sidwiskers/hermes/session",
	"github.com/sidwiskers/hermes/testkit",
	"github.com/sidwiskers/hermes/types",
}

type listedPackage struct {
	ImportPath string
	Export     string
	Error      *struct {
		Err string
	}
}

func main() {
	output := flag.String("output", "spec/api-surface.txt", "manifest output path, or - for stdout")
	flag.Parse()

	manifest, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if *output == "-" {
		_, err = os.Stdout.Write(manifest)
	} else {
		err = os.WriteFile(*output, manifest, 0o644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() ([]byte, error) {
	exports, err := exportFiles(publicPackages)
	if err != nil {
		return nil, err
	}
	lookup := func(path string) (io.ReadCloser, error) {
		file, ok := exports[path]
		if !ok || file == "" {
			return nil, fmt.Errorf("api-surface: no export data for %s", path)
		}
		return os.Open(file)
	}
	load := importer.ForCompiler(token.NewFileSet(), runtime.Compiler, lookup)

	var buffer bytes.Buffer
	buffer.WriteString("# Code generated by go run ./internal/cmd/api-surface; DO NOT EDIT.\n")
	buffer.WriteString("# One declaration per line. Changes require an intentional compatibility review.\n")
	for _, path := range publicPackages {
		pkg, err := load.Import(path)
		if err != nil {
			return nil, fmt.Errorf("api-surface: import %s: %w", path, err)
		}
		writePackage(&buffer, pkg)
	}
	return buffer.Bytes(), nil
}

func exportFiles(patterns []string) (map[string]string, error) {
	arguments := append([]string{"list", "-deps", "-export", "-json"}, patterns...)
	command := exec.Command("go", arguments...)
	output, err := command.Output()
	if err != nil {
		if exit, ok := err.(*exec.ExitError); ok {
			return nil, fmt.Errorf("api-surface: go list: %s", strings.TrimSpace(string(exit.Stderr)))
		}
		return nil, fmt.Errorf("api-surface: go list: %w", err)
	}

	exports := make(map[string]string)
	decoder := json.NewDecoder(bytes.NewReader(output))
	for {
		var pkg listedPackage
		if err := decoder.Decode(&pkg); err != nil {
			if err == io.EOF {
				break
			}
			return nil, fmt.Errorf("api-surface: decode go list: %w", err)
		}
		if pkg.Error != nil {
			return nil, fmt.Errorf("api-surface: go list %s: %s", pkg.ImportPath, pkg.Error.Err)
		}
		if pkg.Export != "" {
			exports[pkg.ImportPath] = filepath.Clean(pkg.Export)
		}
	}
	return exports, nil
}

func writePackage(buffer *bytes.Buffer, pkg *types.Package) {
	fmt.Fprintf(buffer, "\npackage %s\n", pkg.Path())
	qualifier := func(other *types.Package) string {
		if other == nil || other.Path() == pkg.Path() {
			return ""
		}
		return other.Path()
	}

	scope := pkg.Scope()
	for _, name := range scope.Names() {
		if !token.IsExported(name) {
			continue
		}
		object := scope.Lookup(name)
		switch object := object.(type) {
		case *types.Const:
			fmt.Fprintf(buffer, "const %s %s = %s\n", name, types.TypeString(object.Type(), qualifier), object.Val().ExactString())
		case *types.Var:
			fmt.Fprintf(buffer, "var %s %s\n", name, types.TypeString(object.Type(), qualifier))
		case *types.Func:
			fmt.Fprintf(buffer, "func %s%s\n", name, signature(object.Type(), qualifier))
		case *types.TypeName:
			writeType(buffer, object, qualifier)
		}
	}
}

func writeType(buffer *bytes.Buffer, object *types.TypeName, qualifier types.Qualifier) {
	if object.IsAlias() {
		fmt.Fprintf(buffer, "type %s = %s\n", object.Name(), types.TypeString(types.Unalias(object.Type()), qualifier))
		return
	}

	named, ok := object.Type().(*types.Named)
	if !ok {
		fmt.Fprintf(buffer, "type %s %s\n", object.Name(), types.TypeString(object.Type().Underlying(), qualifier))
		return
	}
	fmt.Fprintf(buffer, "type %s%s %s\n", object.Name(), typeParameters(named.TypeParams(), qualifier), underlyingString(named.Underlying(), qualifier))

	methods := make([]*types.Func, 0, named.NumMethods())
	for index := 0; index < named.NumMethods(); index++ {
		method := named.Method(index)
		if method.Exported() {
			methods = append(methods, method)
		}
	}
	sort.Slice(methods, func(left, right int) bool { return methods[left].Name() < methods[right].Name() })
	for _, method := range methods {
		sig := method.Type().(*types.Signature)
		fmt.Fprintf(buffer, "method (%s) %s%s\n", types.TypeString(sig.Recv().Type(), qualifier), method.Name(), signature(sig, qualifier))
	}
}

func underlyingString(value types.Type, qualifier types.Qualifier) string {
	structure, ok := value.(*types.Struct)
	if !ok {
		return types.TypeString(value, qualifier)
	}
	fields := make([]string, 0, structure.NumFields())
	for index := 0; index < structure.NumFields(); index++ {
		field := structure.Field(index)
		if !field.Exported() {
			continue
		}
		declaration := types.TypeString(field.Type(), qualifier)
		if !field.Embedded() {
			declaration = field.Name() + " " + declaration
		}
		if tag := structure.Tag(index); tag != "" {
			declaration += " `" + tag + "`"
		}
		fields = append(fields, declaration)
	}
	if len(fields) == 0 {
		return "struct{}"
	}
	return "struct{" + strings.Join(fields, "; ") + "}"
}

func signature(value types.Type, qualifier types.Qualifier) string {
	text := types.TypeString(value, qualifier)
	return strings.TrimPrefix(text, "func")
}

func typeParameters(list *types.TypeParamList, qualifier types.Qualifier) string {
	if list == nil || list.Len() == 0 {
		return ""
	}
	parts := make([]string, list.Len())
	for index := range list.Len() {
		parameter := list.At(index)
		parts[index] = parameter.Obj().Name() + " " + types.TypeString(parameter.Constraint(), qualifier)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}
