// Code generated by botapi-models from Bot API 10.2; DO NOT EDIT.

package types

// BackgroundFillFreeformGradient mirrors the object defined by the Telegram Bot API.
type BackgroundFillFreeformGradient struct {
	Type   string `json:"type"`
	Colors []int  `json:"colors"`
}

// BackgroundFillGradient mirrors the object defined by the Telegram Bot API.
type BackgroundFillGradient struct {
	Type          string `json:"type"`
	TopColor      int    `json:"top_color"`
	BottomColor   int    `json:"bottom_color"`
	RotationAngle int    `json:"rotation_angle"`
}

// BackgroundFillSolid mirrors the object defined by the Telegram Bot API.
type BackgroundFillSolid struct {
	Type  string `json:"type"`
	Color int    `json:"color"`
}

// BackgroundTypeChatTheme mirrors the object defined by the Telegram Bot API.
type BackgroundTypeChatTheme struct {
	Type      string `json:"type"`
	ThemeName string `json:"theme_name"`
}

// BackgroundTypeFill mirrors the object defined by the Telegram Bot API.
type BackgroundTypeFill struct {
	Type             string         `json:"type"`
	Fill             BackgroundFill `json:"fill"`
	DarkThemeDimming int            `json:"dark_theme_dimming"`
}

// BackgroundTypePattern mirrors the object defined by the Telegram Bot API.
type BackgroundTypePattern struct {
	Type       string         `json:"type"`
	Document   Document       `json:"document"`
	Fill       BackgroundFill `json:"fill"`
	Intensity  int            `json:"intensity"`
	IsInverted bool           `json:"is_inverted,omitempty"`
	IsMoving   bool           `json:"is_moving,omitempty"`
}

// BackgroundTypeWallpaper mirrors the object defined by the Telegram Bot API.
type BackgroundTypeWallpaper struct {
	Type             string   `json:"type"`
	Document         Document `json:"document"`
	DarkThemeDimming int      `json:"dark_theme_dimming"`
	IsBlurred        bool     `json:"is_blurred,omitempty"`
	IsMoving         bool     `json:"is_moving,omitempty"`
}

// Birthdate mirrors the object defined by the Telegram Bot API.
type Birthdate struct {
	Day   int `json:"day"`
	Month int `json:"month"`
	Year  int `json:"year,omitempty"`
}

// BusinessIntro mirrors the object defined by the Telegram Bot API.
type BusinessIntro struct {
	Title   string   `json:"title,omitempty"`
	Message string   `json:"message,omitempty"`
	Sticker *Sticker `json:"sticker,omitempty"`
}

// BusinessLocation mirrors the object defined by the Telegram Bot API.
type BusinessLocation struct {
	Address  string    `json:"address"`
	Location *Location `json:"location,omitempty"`
}

// BusinessOpeningHours mirrors the object defined by the Telegram Bot API.
type BusinessOpeningHours struct {
	TimeZoneName string                         `json:"time_zone_name"`
	OpeningHours []BusinessOpeningHoursInterval `json:"opening_hours"`
}

// BusinessOpeningHoursInterval mirrors the object defined by the Telegram Bot API.
type BusinessOpeningHoursInterval struct {
	OpeningMinute int `json:"opening_minute"`
	ClosingMinute int `json:"closing_minute"`
}

// ChatBackground mirrors the object defined by the Telegram Bot API.
type ChatBackground struct {
	Type BackgroundType `json:"type"`
}

// ChatBoostAdded mirrors the object defined by the Telegram Bot API.
type ChatBoostAdded struct {
	BoostCount int `json:"boost_count"`
}

// ChatBoostSourceGiftCode mirrors the object defined by the Telegram Bot API.
type ChatBoostSourceGiftCode struct {
	Source string `json:"source"`
	User   User   `json:"user"`
}

// ChatBoostSourceGiveaway mirrors the object defined by the Telegram Bot API.
type ChatBoostSourceGiveaway struct {
	Source            string `json:"source"`
	GiveawayMessageID int    `json:"giveaway_message_id"`
	User              *User  `json:"user,omitempty"`
	PrizeStarCount    int    `json:"prize_star_count,omitempty"`
	IsUnclaimed       bool   `json:"is_unclaimed,omitempty"`
}

// ChatBoostSourcePremium mirrors the object defined by the Telegram Bot API.
type ChatBoostSourcePremium struct {
	Source string `json:"source"`
	User   User   `json:"user"`
}

// ChatFullInfoBotAPIFields mirrors the object defined by the Telegram Bot API.
type ChatFullInfoBotAPIFields struct {
	Photo                              *ChatPhoto            `json:"photo,omitempty"`
	Birthdate                          *Birthdate            `json:"birthdate,omitempty"`
	BusinessIntro                      *BusinessIntro        `json:"business_intro,omitempty"`
	BusinessLocation                   *BusinessLocation     `json:"business_location,omitempty"`
	BusinessOpeningHours               *BusinessOpeningHours `json:"business_opening_hours,omitempty"`
	PersonalChat                       *Chat                 `json:"personal_chat,omitempty"`
	ParentChat                         *Chat                 `json:"parent_chat,omitempty"`
	AvailableReactions                 []ReactionType        `json:"available_reactions,omitempty"`
	BackgroundCustomEmojiID            string                `json:"background_custom_emoji_id,omitempty"`
	ProfileAccentColorID               int                   `json:"profile_accent_color_id,omitempty"`
	ProfileBackgroundCustomEmojiID     string                `json:"profile_background_custom_emoji_id,omitempty"`
	EmojiStatusCustomEmojiID           string                `json:"emoji_status_custom_emoji_id,omitempty"`
	EmojiStatusExpirationDate          int64                 `json:"emoji_status_expiration_date,omitempty"`
	HasPrivateForwards                 bool                  `json:"has_private_forwards,omitempty"`
	HasRestrictedVoiceAndVideoMessages bool                  `json:"has_restricted_voice_and_video_messages,omitempty"`
	JoinToSendMessages                 bool                  `json:"join_to_send_messages,omitempty"`
	JoinByRequest                      bool                  `json:"join_by_request,omitempty"`
	Permissions                        *ChatPermissions      `json:"permissions,omitempty"`
	AcceptedGiftTypes                  AcceptedGiftTypes     `json:"accepted_gift_types"`
	CanSendPaidMedia                   bool                  `json:"can_send_paid_media,omitempty"`
	UnrestrictBoostCount               int                   `json:"unrestrict_boost_count,omitempty"`
	CustomEmojiStickerSetName          string                `json:"custom_emoji_sticker_set_name,omitempty"`
	Location                           *ChatLocation         `json:"location,omitempty"`
	Rating                             *UserRating           `json:"rating,omitempty"`
	FirstProfileAudio                  *Audio                `json:"first_profile_audio,omitempty"`
	UniqueGiftColors                   *UniqueGiftColors     `json:"unique_gift_colors,omitempty"`
	PaidMessageStarCount               int                   `json:"paid_message_star_count,omitempty"`
	GuardBot                           *User                 `json:"guard_bot,omitempty"`
}

// ChatJoinRequestBotAPIFields mirrors the object defined by the Telegram Bot API.
type ChatJoinRequestBotAPIFields struct {
	InviteLink *ChatInviteLink `json:"invite_link,omitempty"`
}

// ChatLocation mirrors the object defined by the Telegram Bot API.
type ChatLocation struct {
	Location Location `json:"location"`
	Address  string   `json:"address"`
}

// ChatMemberAdministrator mirrors the object defined by the Telegram Bot API.
type ChatMemberAdministrator struct {
	Status                  string `json:"status"`
	User                    User   `json:"user"`
	CanBeEdited             bool   `json:"can_be_edited"`
	IsAnonymous             bool   `json:"is_anonymous"`
	CanManageChat           bool   `json:"can_manage_chat"`
	CanDeleteMessages       bool   `json:"can_delete_messages"`
	CanManageVideoChats     bool   `json:"can_manage_video_chats"`
	CanRestrictMembers      bool   `json:"can_restrict_members"`
	CanPromoteMembers       bool   `json:"can_promote_members"`
	CanChangeInfo           bool   `json:"can_change_info"`
	CanInviteUsers          bool   `json:"can_invite_users"`
	CanPostStories          bool   `json:"can_post_stories"`
	CanEditStories          bool   `json:"can_edit_stories"`
	CanDeleteStories        bool   `json:"can_delete_stories"`
	CanPostMessages         bool   `json:"can_post_messages,omitempty"`
	CanEditMessages         bool   `json:"can_edit_messages,omitempty"`
	CanPinMessages          bool   `json:"can_pin_messages,omitempty"`
	CanManageTopics         bool   `json:"can_manage_topics,omitempty"`
	CanManageDirectMessages bool   `json:"can_manage_direct_messages,omitempty"`
	CanManageTags           bool   `json:"can_manage_tags,omitempty"`
	CustomTitle             string `json:"custom_title,omitempty"`
}

// ChatMemberBanned mirrors the object defined by the Telegram Bot API.
type ChatMemberBanned struct {
	Status    string `json:"status"`
	User      User   `json:"user"`
	UntilDate int64  `json:"until_date"`
}

// ChatMemberLeft mirrors the object defined by the Telegram Bot API.
type ChatMemberLeft struct {
	Status string `json:"status"`
	User   User   `json:"user"`
}

// ChatMemberMember mirrors the object defined by the Telegram Bot API.
type ChatMemberMember struct {
	Status    string `json:"status"`
	Tag       string `json:"tag,omitempty"`
	User      User   `json:"user"`
	UntilDate int64  `json:"until_date,omitempty"`
}

// ChatMemberOwner mirrors the object defined by the Telegram Bot API.
type ChatMemberOwner struct {
	Status      string `json:"status"`
	User        User   `json:"user"`
	IsAnonymous bool   `json:"is_anonymous"`
	CustomTitle string `json:"custom_title,omitempty"`
}

// ChatMemberRestricted mirrors the object defined by the Telegram Bot API.
type ChatMemberRestricted struct {
	Status                string `json:"status"`
	Tag                   string `json:"tag,omitempty"`
	User                  User   `json:"user"`
	IsMember              bool   `json:"is_member"`
	CanSendMessages       bool   `json:"can_send_messages"`
	CanSendAudios         bool   `json:"can_send_audios"`
	CanSendDocuments      bool   `json:"can_send_documents"`
	CanSendPhotos         bool   `json:"can_send_photos"`
	CanSendVideos         bool   `json:"can_send_videos"`
	CanSendVideoNotes     bool   `json:"can_send_video_notes"`
	CanSendVoiceNotes     bool   `json:"can_send_voice_notes"`
	CanSendPolls          bool   `json:"can_send_polls"`
	CanSendOtherMessages  bool   `json:"can_send_other_messages"`
	CanAddWebPagePreviews bool   `json:"can_add_web_page_previews"`
	CanReactToMessages    bool   `json:"can_react_to_messages"`
	CanEditTag            bool   `json:"can_edit_tag"`
	CanChangeInfo         bool   `json:"can_change_info"`
	CanInviteUsers        bool   `json:"can_invite_users"`
	CanPinMessages        bool   `json:"can_pin_messages"`
	CanManageTopics       bool   `json:"can_manage_topics"`
	UntilDate             int64  `json:"until_date"`
}

// ChatMemberUpdatedBotAPIFields mirrors the object defined by the Telegram Bot API.
type ChatMemberUpdatedBotAPIFields struct {
	InviteLink              *ChatInviteLink `json:"invite_link,omitempty"`
	ViaJoinRequest          bool            `json:"via_join_request,omitempty"`
	ViaChatFolderInviteLink bool            `json:"via_chat_folder_invite_link,omitempty"`
}

// ChatOwnerChanged mirrors the object defined by the Telegram Bot API.
type ChatOwnerChanged struct {
	NewOwner User `json:"new_owner"`
}

// ChatOwnerLeft mirrors the object defined by the Telegram Bot API.
type ChatOwnerLeft struct {
	NewOwner *User `json:"new_owner,omitempty"`
}

// ChatPhoto mirrors the object defined by the Telegram Bot API.
type ChatPhoto struct {
	SmallFileID       string `json:"small_file_id"`
	SmallFileUniqueID string `json:"small_file_unique_id"`
	BigFileID         string `json:"big_file_id"`
	BigFileUniqueID   string `json:"big_file_unique_id"`
}

// ChatShared mirrors the object defined by the Telegram Bot API.
type ChatShared struct {
	RequestID int         `json:"request_id"`
	ChatID    int64       `json:"chat_id"`
	Title     string      `json:"title,omitempty"`
	Username  string      `json:"username,omitempty"`
	Photo     []PhotoSize `json:"photo,omitempty"`
}

// ChecklistTasksAdded mirrors the object defined by the Telegram Bot API.
type ChecklistTasksAdded struct {
	ChecklistMessage *Message        `json:"checklist_message,omitempty"`
	Tasks            []ChecklistTask `json:"tasks"`
}

// ChecklistTasksDone mirrors the object defined by the Telegram Bot API.
type ChecklistTasksDone struct {
	ChecklistMessage       *Message `json:"checklist_message,omitempty"`
	MarkedAsDoneTaskIDs    []int    `json:"marked_as_done_task_ids,omitempty"`
	MarkedAsNotDoneTaskIDs []int    `json:"marked_as_not_done_task_ids,omitempty"`
}

// DirectMessagePriceChanged mirrors the object defined by the Telegram Bot API.
type DirectMessagePriceChanged struct {
	AreDirectMessagesEnabled bool `json:"are_direct_messages_enabled"`
	DirectMessageStarCount   int  `json:"direct_message_star_count,omitempty"`
}

// DirectMessagesTopic mirrors the object defined by the Telegram Bot API.
type DirectMessagesTopic struct {
	TopicID int   `json:"topic_id"`
	User    *User `json:"user,omitempty"`
}

// EncryptedCredentials mirrors the object defined by the Telegram Bot API.
type EncryptedCredentials struct {
	Data   string `json:"data"`
	Hash   string `json:"hash"`
	Secret string `json:"secret"`
}

// EncryptedPassportElement mirrors the object defined by the Telegram Bot API.
type EncryptedPassportElement struct {
	Type        string         `json:"type"`
	Data        string         `json:"data,omitempty"`
	PhoneNumber string         `json:"phone_number,omitempty"`
	Email       string         `json:"email,omitempty"`
	Files       []PassportFile `json:"files,omitempty"`
	FrontSide   *PassportFile  `json:"front_side,omitempty"`
	ReverseSide *PassportFile  `json:"reverse_side,omitempty"`
	Selfie      *PassportFile  `json:"selfie,omitempty"`
	Translation []PassportFile `json:"translation,omitempty"`
	Hash        string         `json:"hash"`
}

// ExternalReplyInfo mirrors the object defined by the Telegram Bot API.
type ExternalReplyInfo struct {
	Origin             MessageOrigin       `json:"origin"`
	Chat               *Chat               `json:"chat,omitempty"`
	MessageID          int                 `json:"message_id,omitempty"`
	LinkPreviewOptions *LinkPreviewOptions `json:"link_preview_options,omitempty"`
	Animation          *Animation          `json:"animation,omitempty"`
	Audio              *Audio              `json:"audio,omitempty"`
	Document           *Document           `json:"document,omitempty"`
	LivePhoto          *LivePhoto          `json:"live_photo,omitempty"`
	PaidMedia          *PaidMediaInfo      `json:"paid_media,omitempty"`
	Photo              []PhotoSize         `json:"photo,omitempty"`
	Sticker            *Sticker            `json:"sticker,omitempty"`
	Story              *Story              `json:"story,omitempty"`
	Video              *Video              `json:"video,omitempty"`
	VideoNote          *VideoNote          `json:"video_note,omitempty"`
	Voice              *Voice              `json:"voice,omitempty"`
	HasMediaSpoiler    bool                `json:"has_media_spoiler,omitempty"`
	Checklist          *Checklist          `json:"checklist,omitempty"`
	Contact            *Contact            `json:"contact,omitempty"`
	Dice               *Dice               `json:"dice,omitempty"`
	Game               *Game               `json:"game,omitempty"`
	Giveaway           *Giveaway           `json:"giveaway,omitempty"`
	GiveawayWinners    *GiveawayWinners    `json:"giveaway_winners,omitempty"`
	Invoice            *Invoice            `json:"invoice,omitempty"`
	Location           *Location           `json:"location,omitempty"`
	Poll               *Poll               `json:"poll,omitempty"`
	Venue              *Venue              `json:"venue,omitempty"`
}

// ForumTopicClosed mirrors the object defined by the Telegram Bot API.
type ForumTopicClosed struct {
}

// ForumTopicCreated mirrors the object defined by the Telegram Bot API.
type ForumTopicCreated struct {
	Name              string `json:"name"`
	IconColor         int    `json:"icon_color"`
	IconCustomEmojiID string `json:"icon_custom_emoji_id,omitempty"`
	IsNameImplicit    bool   `json:"is_name_implicit,omitempty"`
}

// ForumTopicEdited mirrors the object defined by the Telegram Bot API.
type ForumTopicEdited struct {
	Name              string `json:"name,omitempty"`
	IconCustomEmojiID string `json:"icon_custom_emoji_id,omitempty"`
}

// ForumTopicReopened mirrors the object defined by the Telegram Bot API.
type ForumTopicReopened struct {
}

// GeneralForumTopicHidden mirrors the object defined by the Telegram Bot API.
type GeneralForumTopicHidden struct {
}

// GeneralForumTopicUnhidden mirrors the object defined by the Telegram Bot API.
type GeneralForumTopicUnhidden struct {
}

// GiftInfo mirrors the object defined by the Telegram Bot API.
type GiftInfo struct {
	Gift                    Gift            `json:"gift"`
	OwnedGiftID             string          `json:"owned_gift_id,omitempty"`
	ConvertStarCount        int             `json:"convert_star_count,omitempty"`
	PrepaidUpgradeStarCount int             `json:"prepaid_upgrade_star_count,omitempty"`
	IsUpgradeSeparate       bool            `json:"is_upgrade_separate,omitempty"`
	CanBeUpgraded           bool            `json:"can_be_upgraded,omitempty"`
	Text                    string          `json:"text,omitempty"`
	Entities                []MessageEntity `json:"entities,omitempty"`
	IsPrivate               bool            `json:"is_private,omitempty"`
	UniqueGiftNumber        int             `json:"unique_gift_number,omitempty"`
}

// Giveaway mirrors the object defined by the Telegram Bot API.
type Giveaway struct {
	Chats                         []Chat   `json:"chats"`
	WinnersSelectionDate          int64    `json:"winners_selection_date"`
	WinnerCount                   int      `json:"winner_count"`
	OnlyNewMembers                bool     `json:"only_new_members,omitempty"`
	HasPublicWinners              bool     `json:"has_public_winners,omitempty"`
	PrizeDescription              string   `json:"prize_description,omitempty"`
	CountryCodes                  []string `json:"country_codes,omitempty"`
	PrizeStarCount                int      `json:"prize_star_count,omitempty"`
	PremiumSubscriptionMonthCount int      `json:"premium_subscription_month_count,omitempty"`
}

// GiveawayCompleted mirrors the object defined by the Telegram Bot API.
type GiveawayCompleted struct {
	WinnerCount         int      `json:"winner_count"`
	UnclaimedPrizeCount int      `json:"unclaimed_prize_count,omitempty"`
	GiveawayMessage     *Message `json:"giveaway_message,omitempty"`
	IsStarGiveaway      bool     `json:"is_star_giveaway,omitempty"`
}

// GiveawayCreated mirrors the object defined by the Telegram Bot API.
type GiveawayCreated struct {
	PrizeStarCount int `json:"prize_star_count,omitempty"`
}

// GiveawayWinners mirrors the object defined by the Telegram Bot API.
type GiveawayWinners struct {
	Chat                          Chat   `json:"chat"`
	GiveawayMessageID             int    `json:"giveaway_message_id"`
	WinnersSelectionDate          int64  `json:"winners_selection_date"`
	WinnerCount                   int    `json:"winner_count"`
	Winners                       []User `json:"winners"`
	AdditionalChatCount           int    `json:"additional_chat_count,omitempty"`
	PrizeStarCount                int    `json:"prize_star_count,omitempty"`
	PremiumSubscriptionMonthCount int    `json:"premium_subscription_month_count,omitempty"`
	UnclaimedPrizeCount           int    `json:"unclaimed_prize_count,omitempty"`
	OnlyNewMembers                bool   `json:"only_new_members,omitempty"`
	WasRefunded                   bool   `json:"was_refunded,omitempty"`
	PrizeDescription              string `json:"prize_description,omitempty"`
}

// InaccessibleMessage mirrors the object defined by the Telegram Bot API.
type InaccessibleMessage struct {
	Chat      Chat  `json:"chat"`
	MessageID int   `json:"message_id"`
	Date      int64 `json:"date"`
}

// InlineKeyboardButtonBotAPIFields mirrors the object defined by the Telegram Bot API.
type InlineKeyboardButtonBotAPIFields struct {
	IconCustomEmojiID string `json:"icon_custom_emoji_id,omitempty"`
	Style             string `json:"style,omitempty"`
}

// InlineQueryResultArticle mirrors the object defined by the Telegram Bot API.
type InlineQueryResultArticle struct {
	ID                  string                `json:"id"`
	Title               string                `json:"title"`
	InputMessageContent InputMessageContent   `json:"input_message_content"`
	ReplyMarkup         *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	URL                 string                `json:"url,omitempty"`
	Description         string                `json:"description,omitempty"`
	ThumbnailURL        string                `json:"thumbnail_url,omitempty"`
	ThumbnailWidth      int                   `json:"thumbnail_width,omitempty"`
	ThumbnailHeight     int                   `json:"thumbnail_height,omitempty"`
}

func (InlineQueryResultArticle) inlineQueryResult() {}

func (InlineQueryResultArticle) InlineQueryResultType() string { return "article" }

func (value InlineQueryResultArticle) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultArticle) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultArticle
	return marshalDiscriminated("article", plain(value))
}

// InlineQueryResultAudio mirrors the object defined by the Telegram Bot API.
type InlineQueryResultAudio struct {
	ID                  string                `json:"id"`
	AudioURL            string                `json:"audio_url"`
	Title               string                `json:"title"`
	Caption             string                `json:"caption,omitempty"`
	ParseMode           string                `json:"parse_mode,omitempty"`
	CaptionEntities     []MessageEntity       `json:"caption_entities,omitempty"`
	Performer           string                `json:"performer,omitempty"`
	AudioDuration       int                   `json:"audio_duration,omitempty"`
	ReplyMarkup         *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultAudio) inlineQueryResult() {}

func (InlineQueryResultAudio) InlineQueryResultType() string { return "audio" }

func (value InlineQueryResultAudio) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultAudio) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultAudio
	return marshalDiscriminated("audio", plain(value))
}

// InlineQueryResultCachedAudio mirrors the object defined by the Telegram Bot API.
type InlineQueryResultCachedAudio struct {
	ID                  string                `json:"id"`
	AudioFileID         string                `json:"audio_file_id"`
	Caption             string                `json:"caption,omitempty"`
	ParseMode           string                `json:"parse_mode,omitempty"`
	CaptionEntities     []MessageEntity       `json:"caption_entities,omitempty"`
	ReplyMarkup         *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultCachedAudio) inlineQueryResult() {}

func (InlineQueryResultCachedAudio) InlineQueryResultType() string { return "audio" }

func (value InlineQueryResultCachedAudio) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultCachedAudio) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultCachedAudio
	return marshalDiscriminated("audio", plain(value))
}

// InlineQueryResultCachedDocument mirrors the object defined by the Telegram Bot API.
type InlineQueryResultCachedDocument struct {
	ID                  string                `json:"id"`
	Title               string                `json:"title"`
	DocumentFileID      string                `json:"document_file_id"`
	Description         string                `json:"description,omitempty"`
	Caption             string                `json:"caption,omitempty"`
	ParseMode           string                `json:"parse_mode,omitempty"`
	CaptionEntities     []MessageEntity       `json:"caption_entities,omitempty"`
	ReplyMarkup         *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultCachedDocument) inlineQueryResult() {}

func (InlineQueryResultCachedDocument) InlineQueryResultType() string { return "document" }

func (value InlineQueryResultCachedDocument) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultCachedDocument) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultCachedDocument
	return marshalDiscriminated("document", plain(value))
}

// InlineQueryResultCachedGif mirrors the object defined by the Telegram Bot API.
type InlineQueryResultCachedGif struct {
	ID                    string                `json:"id"`
	GIFFileID             string                `json:"gif_file_id"`
	Title                 string                `json:"title,omitempty"`
	Caption               string                `json:"caption,omitempty"`
	ParseMode             string                `json:"parse_mode,omitempty"`
	CaptionEntities       []MessageEntity       `json:"caption_entities,omitempty"`
	ShowCaptionAboveMedia bool                  `json:"show_caption_above_media,omitempty"`
	ReplyMarkup           *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent   InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultCachedGif) inlineQueryResult() {}

func (InlineQueryResultCachedGif) InlineQueryResultType() string { return "gif" }

func (value InlineQueryResultCachedGif) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultCachedGif) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultCachedGif
	return marshalDiscriminated("gif", plain(value))
}

// InlineQueryResultCachedMpeg4Gif mirrors the object defined by the Telegram Bot API.
type InlineQueryResultCachedMpeg4Gif struct {
	ID                    string                `json:"id"`
	MPEG4FileID           string                `json:"mpeg4_file_id"`
	Title                 string                `json:"title,omitempty"`
	Caption               string                `json:"caption,omitempty"`
	ParseMode             string                `json:"parse_mode,omitempty"`
	CaptionEntities       []MessageEntity       `json:"caption_entities,omitempty"`
	ShowCaptionAboveMedia bool                  `json:"show_caption_above_media,omitempty"`
	ReplyMarkup           *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent   InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultCachedMpeg4Gif) inlineQueryResult() {}

func (InlineQueryResultCachedMpeg4Gif) InlineQueryResultType() string { return "mpeg4_gif" }

func (value InlineQueryResultCachedMpeg4Gif) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultCachedMpeg4Gif) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultCachedMpeg4Gif
	return marshalDiscriminated("mpeg4_gif", plain(value))
}

// InlineQueryResultCachedPhoto mirrors the object defined by the Telegram Bot API.
type InlineQueryResultCachedPhoto struct {
	ID                    string                `json:"id"`
	PhotoFileID           string                `json:"photo_file_id"`
	Title                 string                `json:"title,omitempty"`
	Description           string                `json:"description,omitempty"`
	Caption               string                `json:"caption,omitempty"`
	ParseMode             string                `json:"parse_mode,omitempty"`
	CaptionEntities       []MessageEntity       `json:"caption_entities,omitempty"`
	ShowCaptionAboveMedia bool                  `json:"show_caption_above_media,omitempty"`
	ReplyMarkup           *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent   InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultCachedPhoto) inlineQueryResult() {}

func (InlineQueryResultCachedPhoto) InlineQueryResultType() string { return "photo" }

func (value InlineQueryResultCachedPhoto) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultCachedPhoto) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultCachedPhoto
	return marshalDiscriminated("photo", plain(value))
}

// InlineQueryResultCachedSticker mirrors the object defined by the Telegram Bot API.
type InlineQueryResultCachedSticker struct {
	ID                  string                `json:"id"`
	StickerFileID       string                `json:"sticker_file_id"`
	ReplyMarkup         *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultCachedSticker) inlineQueryResult() {}

func (InlineQueryResultCachedSticker) InlineQueryResultType() string { return "sticker" }

func (value InlineQueryResultCachedSticker) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultCachedSticker) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultCachedSticker
	return marshalDiscriminated("sticker", plain(value))
}

// InlineQueryResultCachedVideo mirrors the object defined by the Telegram Bot API.
type InlineQueryResultCachedVideo struct {
	ID                    string                `json:"id"`
	VideoFileID           string                `json:"video_file_id"`
	Title                 string                `json:"title"`
	Description           string                `json:"description,omitempty"`
	Caption               string                `json:"caption,omitempty"`
	ParseMode             string                `json:"parse_mode,omitempty"`
	CaptionEntities       []MessageEntity       `json:"caption_entities,omitempty"`
	ShowCaptionAboveMedia bool                  `json:"show_caption_above_media,omitempty"`
	ReplyMarkup           *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent   InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultCachedVideo) inlineQueryResult() {}

func (InlineQueryResultCachedVideo) InlineQueryResultType() string { return "video" }

func (value InlineQueryResultCachedVideo) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultCachedVideo) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultCachedVideo
	return marshalDiscriminated("video", plain(value))
}

// InlineQueryResultCachedVoice mirrors the object defined by the Telegram Bot API.
type InlineQueryResultCachedVoice struct {
	ID                  string                `json:"id"`
	VoiceFileID         string                `json:"voice_file_id"`
	Title               string                `json:"title"`
	Caption             string                `json:"caption,omitempty"`
	ParseMode           string                `json:"parse_mode,omitempty"`
	CaptionEntities     []MessageEntity       `json:"caption_entities,omitempty"`
	ReplyMarkup         *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultCachedVoice) inlineQueryResult() {}

func (InlineQueryResultCachedVoice) InlineQueryResultType() string { return "voice" }

func (value InlineQueryResultCachedVoice) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultCachedVoice) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultCachedVoice
	return marshalDiscriminated("voice", plain(value))
}

// InlineQueryResultContact mirrors the object defined by the Telegram Bot API.
type InlineQueryResultContact struct {
	ID                  string                `json:"id"`
	PhoneNumber         string                `json:"phone_number"`
	FirstName           string                `json:"first_name"`
	LastName            string                `json:"last_name,omitempty"`
	VCard               string                `json:"vcard,omitempty"`
	ReplyMarkup         *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent InputMessageContent   `json:"input_message_content,omitempty"`
	ThumbnailURL        string                `json:"thumbnail_url,omitempty"`
	ThumbnailWidth      int                   `json:"thumbnail_width,omitempty"`
	ThumbnailHeight     int                   `json:"thumbnail_height,omitempty"`
}

func (InlineQueryResultContact) inlineQueryResult() {}

func (InlineQueryResultContact) InlineQueryResultType() string { return "contact" }

func (value InlineQueryResultContact) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultContact) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultContact
	return marshalDiscriminated("contact", plain(value))
}

// InlineQueryResultDocument mirrors the object defined by the Telegram Bot API.
type InlineQueryResultDocument struct {
	ID                  string                `json:"id"`
	Title               string                `json:"title"`
	Caption             string                `json:"caption,omitempty"`
	ParseMode           string                `json:"parse_mode,omitempty"`
	CaptionEntities     []MessageEntity       `json:"caption_entities,omitempty"`
	DocumentURL         string                `json:"document_url"`
	MIMEType            string                `json:"mime_type"`
	Description         string                `json:"description,omitempty"`
	ReplyMarkup         *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent InputMessageContent   `json:"input_message_content,omitempty"`
	ThumbnailURL        string                `json:"thumbnail_url,omitempty"`
	ThumbnailWidth      int                   `json:"thumbnail_width,omitempty"`
	ThumbnailHeight     int                   `json:"thumbnail_height,omitempty"`
}

func (InlineQueryResultDocument) inlineQueryResult() {}

func (InlineQueryResultDocument) InlineQueryResultType() string { return "document" }

func (value InlineQueryResultDocument) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultDocument) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultDocument
	return marshalDiscriminated("document", plain(value))
}

// InlineQueryResultGame mirrors the object defined by the Telegram Bot API.
type InlineQueryResultGame struct {
	ID            string                `json:"id"`
	GameShortName string                `json:"game_short_name"`
	ReplyMarkup   *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
}

func (InlineQueryResultGame) inlineQueryResult() {}

func (InlineQueryResultGame) InlineQueryResultType() string { return "game" }

func (value InlineQueryResultGame) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultGame) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultGame
	return marshalDiscriminated("game", plain(value))
}

// InlineQueryResultGif mirrors the object defined by the Telegram Bot API.
type InlineQueryResultGif struct {
	ID                    string                `json:"id"`
	GIFURL                string                `json:"gif_url"`
	GIFWidth              int                   `json:"gif_width,omitempty"`
	GIFHeight             int                   `json:"gif_height,omitempty"`
	GIFDuration           int                   `json:"gif_duration,omitempty"`
	ThumbnailURL          string                `json:"thumbnail_url"`
	ThumbnailMIMEType     string                `json:"thumbnail_mime_type,omitempty"`
	Title                 string                `json:"title,omitempty"`
	Caption               string                `json:"caption,omitempty"`
	ParseMode             string                `json:"parse_mode,omitempty"`
	CaptionEntities       []MessageEntity       `json:"caption_entities,omitempty"`
	ShowCaptionAboveMedia bool                  `json:"show_caption_above_media,omitempty"`
	ReplyMarkup           *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent   InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultGif) inlineQueryResult() {}

func (InlineQueryResultGif) InlineQueryResultType() string { return "gif" }

func (value InlineQueryResultGif) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultGif) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultGif
	return marshalDiscriminated("gif", plain(value))
}

// InlineQueryResultLocation mirrors the object defined by the Telegram Bot API.
type InlineQueryResultLocation struct {
	ID                   string                `json:"id"`
	Latitude             float64               `json:"latitude"`
	Longitude            float64               `json:"longitude"`
	Title                string                `json:"title"`
	HorizontalAccuracy   float64               `json:"horizontal_accuracy,omitempty"`
	LivePeriod           int                   `json:"live_period,omitempty"`
	Heading              int                   `json:"heading,omitempty"`
	ProximityAlertRadius int                   `json:"proximity_alert_radius,omitempty"`
	ReplyMarkup          *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent  InputMessageContent   `json:"input_message_content,omitempty"`
	ThumbnailURL         string                `json:"thumbnail_url,omitempty"`
	ThumbnailWidth       int                   `json:"thumbnail_width,omitempty"`
	ThumbnailHeight      int                   `json:"thumbnail_height,omitempty"`
}

func (InlineQueryResultLocation) inlineQueryResult() {}

func (InlineQueryResultLocation) InlineQueryResultType() string { return "location" }

func (value InlineQueryResultLocation) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultLocation) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultLocation
	return marshalDiscriminated("location", plain(value))
}

// InlineQueryResultMpeg4Gif mirrors the object defined by the Telegram Bot API.
type InlineQueryResultMpeg4Gif struct {
	ID                    string                `json:"id"`
	MPEG4URL              string                `json:"mpeg4_url"`
	MPEG4Width            int                   `json:"mpeg4_width,omitempty"`
	MPEG4Height           int                   `json:"mpeg4_height,omitempty"`
	MPEG4Duration         int                   `json:"mpeg4_duration,omitempty"`
	ThumbnailURL          string                `json:"thumbnail_url"`
	ThumbnailMIMEType     string                `json:"thumbnail_mime_type,omitempty"`
	Title                 string                `json:"title,omitempty"`
	Caption               string                `json:"caption,omitempty"`
	ParseMode             string                `json:"parse_mode,omitempty"`
	CaptionEntities       []MessageEntity       `json:"caption_entities,omitempty"`
	ShowCaptionAboveMedia bool                  `json:"show_caption_above_media,omitempty"`
	ReplyMarkup           *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent   InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultMpeg4Gif) inlineQueryResult() {}

func (InlineQueryResultMpeg4Gif) InlineQueryResultType() string { return "mpeg4_gif" }

func (value InlineQueryResultMpeg4Gif) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultMpeg4Gif) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultMpeg4Gif
	return marshalDiscriminated("mpeg4_gif", plain(value))
}

// InlineQueryResultPhoto mirrors the object defined by the Telegram Bot API.
type InlineQueryResultPhoto struct {
	ID                    string                `json:"id"`
	PhotoURL              string                `json:"photo_url"`
	ThumbnailURL          string                `json:"thumbnail_url"`
	PhotoWidth            int                   `json:"photo_width,omitempty"`
	PhotoHeight           int                   `json:"photo_height,omitempty"`
	Title                 string                `json:"title,omitempty"`
	Description           string                `json:"description,omitempty"`
	Caption               string                `json:"caption,omitempty"`
	ParseMode             string                `json:"parse_mode,omitempty"`
	CaptionEntities       []MessageEntity       `json:"caption_entities,omitempty"`
	ShowCaptionAboveMedia bool                  `json:"show_caption_above_media,omitempty"`
	ReplyMarkup           *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent   InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultPhoto) inlineQueryResult() {}

func (InlineQueryResultPhoto) InlineQueryResultType() string { return "photo" }

func (value InlineQueryResultPhoto) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultPhoto) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultPhoto
	return marshalDiscriminated("photo", plain(value))
}

// InlineQueryResultVenue mirrors the object defined by the Telegram Bot API.
type InlineQueryResultVenue struct {
	ID                  string                `json:"id"`
	Latitude            float64               `json:"latitude"`
	Longitude           float64               `json:"longitude"`
	Title               string                `json:"title"`
	Address             string                `json:"address"`
	FoursquareID        string                `json:"foursquare_id,omitempty"`
	FoursquareType      string                `json:"foursquare_type,omitempty"`
	GooglePlaceID       string                `json:"google_place_id,omitempty"`
	GooglePlaceType     string                `json:"google_place_type,omitempty"`
	ReplyMarkup         *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent InputMessageContent   `json:"input_message_content,omitempty"`
	ThumbnailURL        string                `json:"thumbnail_url,omitempty"`
	ThumbnailWidth      int                   `json:"thumbnail_width,omitempty"`
	ThumbnailHeight     int                   `json:"thumbnail_height,omitempty"`
}

func (InlineQueryResultVenue) inlineQueryResult() {}

func (InlineQueryResultVenue) InlineQueryResultType() string { return "venue" }

func (value InlineQueryResultVenue) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultVenue) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultVenue
	return marshalDiscriminated("venue", plain(value))
}

// InlineQueryResultVideo mirrors the object defined by the Telegram Bot API.
type InlineQueryResultVideo struct {
	ID                    string                `json:"id"`
	VideoURL              string                `json:"video_url"`
	MIMEType              string                `json:"mime_type"`
	ThumbnailURL          string                `json:"thumbnail_url"`
	Title                 string                `json:"title"`
	Caption               string                `json:"caption,omitempty"`
	ParseMode             string                `json:"parse_mode,omitempty"`
	CaptionEntities       []MessageEntity       `json:"caption_entities,omitempty"`
	ShowCaptionAboveMedia bool                  `json:"show_caption_above_media,omitempty"`
	VideoWidth            int                   `json:"video_width,omitempty"`
	VideoHeight           int                   `json:"video_height,omitempty"`
	VideoDuration         int                   `json:"video_duration,omitempty"`
	Description           string                `json:"description,omitempty"`
	ReplyMarkup           *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent   InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultVideo) inlineQueryResult() {}

func (InlineQueryResultVideo) InlineQueryResultType() string { return "video" }

func (value InlineQueryResultVideo) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultVideo) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultVideo
	return marshalDiscriminated("video", plain(value))
}

// InlineQueryResultVoice mirrors the object defined by the Telegram Bot API.
type InlineQueryResultVoice struct {
	ID                  string                `json:"id"`
	VoiceURL            string                `json:"voice_url"`
	Title               string                `json:"title"`
	Caption             string                `json:"caption,omitempty"`
	ParseMode           string                `json:"parse_mode,omitempty"`
	CaptionEntities     []MessageEntity       `json:"caption_entities,omitempty"`
	VoiceDuration       int                   `json:"voice_duration,omitempty"`
	ReplyMarkup         *InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	InputMessageContent InputMessageContent   `json:"input_message_content,omitempty"`
}

func (InlineQueryResultVoice) inlineQueryResult() {}

func (InlineQueryResultVoice) InlineQueryResultType() string { return "voice" }

func (value InlineQueryResultVoice) InlineQueryResultID() string { return value.ID }

func (value InlineQueryResultVoice) MarshalJSON() ([]byte, error) {
	type plain InlineQueryResultVoice
	return marshalDiscriminated("voice", plain(value))
}

// InputContactMessageContent mirrors the object defined by the Telegram Bot API.
type InputContactMessageContent struct {
	PhoneNumber string `json:"phone_number"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name,omitempty"`
	VCard       string `json:"vcard,omitempty"`
}

func (InputContactMessageContent) inputMessageContent() {}

// InputInvoiceMessageContent mirrors the object defined by the Telegram Bot API.
type InputInvoiceMessageContent struct {
	Title                     string         `json:"title"`
	Description               string         `json:"description"`
	Payload                   string         `json:"payload"`
	ProviderToken             string         `json:"provider_token,omitempty"`
	Currency                  string         `json:"currency"`
	Prices                    []LabeledPrice `json:"prices"`
	MaxTipAmount              int            `json:"max_tip_amount,omitempty"`
	SuggestedTipAmounts       []int          `json:"suggested_tip_amounts,omitempty"`
	ProviderData              string         `json:"provider_data,omitempty"`
	PhotoURL                  string         `json:"photo_url,omitempty"`
	PhotoSize                 int            `json:"photo_size,omitempty"`
	PhotoWidth                int            `json:"photo_width,omitempty"`
	PhotoHeight               int            `json:"photo_height,omitempty"`
	NeedName                  bool           `json:"need_name,omitempty"`
	NeedPhoneNumber           bool           `json:"need_phone_number,omitempty"`
	NeedEmail                 bool           `json:"need_email,omitempty"`
	NeedShippingAddress       bool           `json:"need_shipping_address,omitempty"`
	SendPhoneNumberToProvider bool           `json:"send_phone_number_to_provider,omitempty"`
	SendEmailToProvider       bool           `json:"send_email_to_provider,omitempty"`
	IsFlexible                bool           `json:"is_flexible,omitempty"`
}

func (InputInvoiceMessageContent) inputMessageContent() {}

// InputLocationMessageContent mirrors the object defined by the Telegram Bot API.
type InputLocationMessageContent struct {
	Latitude             float64 `json:"latitude"`
	Longitude            float64 `json:"longitude"`
	HorizontalAccuracy   float64 `json:"horizontal_accuracy,omitempty"`
	LivePeriod           int     `json:"live_period,omitempty"`
	Heading              int     `json:"heading,omitempty"`
	ProximityAlertRadius int     `json:"proximity_alert_radius,omitempty"`
}

func (InputLocationMessageContent) inputMessageContent() {}

// InputTextMessageContent mirrors the object defined by the Telegram Bot API.
type InputTextMessageContent struct {
	MessageText        string              `json:"message_text"`
	ParseMode          string              `json:"parse_mode,omitempty"`
	Entities           []MessageEntity     `json:"entities,omitempty"`
	LinkPreviewOptions *LinkPreviewOptions `json:"link_preview_options,omitempty"`
}

func (InputTextMessageContent) inputMessageContent() {}

// InputVenueMessageContent mirrors the object defined by the Telegram Bot API.
type InputVenueMessageContent struct {
	Latitude        float64 `json:"latitude"`
	Longitude       float64 `json:"longitude"`
	Title           string  `json:"title"`
	Address         string  `json:"address"`
	FoursquareID    string  `json:"foursquare_id,omitempty"`
	FoursquareType  string  `json:"foursquare_type,omitempty"`
	GooglePlaceID   string  `json:"google_place_id,omitempty"`
	GooglePlaceType string  `json:"google_place_type,omitempty"`
}

func (InputVenueMessageContent) inputMessageContent() {}

// KeyboardButtonBotAPIFields mirrors the object defined by the Telegram Bot API.
type KeyboardButtonBotAPIFields struct {
	IconCustomEmojiID string `json:"icon_custom_emoji_id,omitempty"`
	Style             string `json:"style,omitempty"`
}

// KeyboardButtonRequestChatBotAPIFields mirrors the object defined by the Telegram Bot API.
type KeyboardButtonRequestChatBotAPIFields struct {
	UserAdministratorRights *ChatAdministratorRights `json:"user_administrator_rights,omitempty"`
	BotAdministratorRights  *ChatAdministratorRights `json:"bot_administrator_rights,omitempty"`
}

// LocationAddress mirrors the object defined by the Telegram Bot API.
type LocationAddress struct {
	CountryCode string `json:"country_code"`
	State       string `json:"state,omitempty"`
	City        string `json:"city,omitempty"`
	Street      string `json:"street,omitempty"`
}

// MenuButtonCommands mirrors the object defined by the Telegram Bot API.
type MenuButtonCommands struct {
	Type string `json:"type"`
}

// MenuButtonDefault mirrors the object defined by the Telegram Bot API.
type MenuButtonDefault struct {
	Type string `json:"type"`
}

// MenuButtonWebApp mirrors the object defined by the Telegram Bot API.
type MenuButtonWebApp struct {
	Type   string     `json:"type"`
	Text   string     `json:"text"`
	WebApp WebAppInfo `json:"web_app"`
}

// MessageBotAPIFields mirrors the object defined by the Telegram Bot API.
type MessageBotAPIFields struct {
	DirectMessagesTopic           *DirectMessagesTopic           `json:"direct_messages_topic,omitempty"`
	SenderBoostCount              int                            `json:"sender_boost_count,omitempty"`
	SenderBusinessBot             *User                          `json:"sender_business_bot,omitempty"`
	SenderTag                     string                         `json:"sender_tag,omitempty"`
	GuestQueryID                  string                         `json:"guest_query_id,omitempty"`
	BusinessConnectionID          string                         `json:"business_connection_id,omitempty"`
	IsTopicMessage                bool                           `json:"is_topic_message,omitempty"`
	IsAutomaticForward            bool                           `json:"is_automatic_forward,omitempty"`
	ExternalReply                 *ExternalReplyInfo             `json:"external_reply,omitempty"`
	Quote                         *TextQuote                     `json:"quote,omitempty"`
	ReplyToStory                  *Story                         `json:"reply_to_story,omitempty"`
	ReplyToChecklistTaskID        int                            `json:"reply_to_checklist_task_id,omitempty"`
	ReplyToPollOptionID           string                         `json:"reply_to_poll_option_id,omitempty"`
	ViaBot                        *User                          `json:"via_bot,omitempty"`
	GuestBotCallerUser            *User                          `json:"guest_bot_caller_user,omitempty"`
	GuestBotCallerChat            *Chat                          `json:"guest_bot_caller_chat,omitempty"`
	EditDate                      int64                          `json:"edit_date,omitempty"`
	HasProtectedContent           bool                           `json:"has_protected_content,omitempty"`
	IsFromOffline                 bool                           `json:"is_from_offline,omitempty"`
	IsPaidPost                    bool                           `json:"is_paid_post,omitempty"`
	AuthorSignature               string                         `json:"author_signature,omitempty"`
	PaidStarCount                 int                            `json:"paid_star_count,omitempty"`
	LinkPreviewOptions            *LinkPreviewOptions            `json:"link_preview_options,omitempty"`
	SuggestedPostInfo             *SuggestedPostInfo             `json:"suggested_post_info,omitempty"`
	EffectID                      string                         `json:"effect_id,omitempty"`
	Story                         *Story                         `json:"story,omitempty"`
	ShowCaptionAboveMedia         bool                           `json:"show_caption_above_media,omitempty"`
	HasMediaSpoiler               bool                           `json:"has_media_spoiler,omitempty"`
	ChatOwnerLeft                 *ChatOwnerLeft                 `json:"chat_owner_left,omitempty"`
	ChatOwnerChanged              *ChatOwnerChanged              `json:"chat_owner_changed,omitempty"`
	NewChatPhoto                  []PhotoSize                    `json:"new_chat_photo,omitempty"`
	MessageAutoDeleteTimerChanged *MessageAutoDeleteTimerChanged `json:"message_auto_delete_timer_changed,omitempty"`
	MigrateToChatID               int64                          `json:"migrate_to_chat_id,omitempty"`
	MigrateFromChatID             int64                          `json:"migrate_from_chat_id,omitempty"`
	UsersShared                   *UsersShared                   `json:"users_shared,omitempty"`
	ChatShared                    *ChatShared                    `json:"chat_shared,omitempty"`
	Gift                          *GiftInfo                      `json:"gift,omitempty"`
	UniqueGift                    *UniqueGiftInfo                `json:"unique_gift,omitempty"`
	GiftUpgradeSent               *GiftInfo                      `json:"gift_upgrade_sent,omitempty"`
	ConnectedWebsite              string                         `json:"connected_website,omitempty"`
	WriteAccessAllowed            *WriteAccessAllowed            `json:"write_access_allowed,omitempty"`
	PassportData                  *PassportData                  `json:"passport_data,omitempty"`
	ProximityAlertTriggered       *ProximityAlertTriggered       `json:"proximity_alert_triggered,omitempty"`
	BoostAdded                    *ChatBoostAdded                `json:"boost_added,omitempty"`
	ChatBackgroundSet             *ChatBackground                `json:"chat_background_set,omitempty"`
	ChecklistTasksDone            *ChecklistTasksDone            `json:"checklist_tasks_done,omitempty"`
	ChecklistTasksAdded           *ChecklistTasksAdded           `json:"checklist_tasks_added,omitempty"`
	DirectMessagePriceChanged     *DirectMessagePriceChanged     `json:"direct_message_price_changed,omitempty"`
	ForumTopicCreated             *ForumTopicCreated             `json:"forum_topic_created,omitempty"`
	ForumTopicEdited              *ForumTopicEdited              `json:"forum_topic_edited,omitempty"`
	ForumTopicClosed              *ForumTopicClosed              `json:"forum_topic_closed,omitempty"`
	ForumTopicReopened            *ForumTopicReopened            `json:"forum_topic_reopened,omitempty"`
	GeneralForumTopicHidden       *GeneralForumTopicHidden       `json:"general_forum_topic_hidden,omitempty"`
	GeneralForumTopicUnhidden     *GeneralForumTopicUnhidden     `json:"general_forum_topic_unhidden,omitempty"`
	GiveawayCreated               *GiveawayCreated               `json:"giveaway_created,omitempty"`
	Giveaway                      *Giveaway                      `json:"giveaway,omitempty"`
	GiveawayWinners               *GiveawayWinners               `json:"giveaway_winners,omitempty"`
	GiveawayCompleted             *GiveawayCompleted             `json:"giveaway_completed,omitempty"`
	PaidMessagePriceChanged       *PaidMessagePriceChanged       `json:"paid_message_price_changed,omitempty"`
	PollOptionAdded               *PollOptionAdded               `json:"poll_option_added,omitempty"`
	PollOptionDeleted             *PollOptionDeleted             `json:"poll_option_deleted,omitempty"`
	SuggestedPostApproved         *SuggestedPostApproved         `json:"suggested_post_approved,omitempty"`
	SuggestedPostApprovalFailed   *SuggestedPostApprovalFailed   `json:"suggested_post_approval_failed,omitempty"`
	SuggestedPostDeclined         *SuggestedPostDeclined         `json:"suggested_post_declined,omitempty"`
	SuggestedPostPaid             *SuggestedPostPaid             `json:"suggested_post_paid,omitempty"`
	SuggestedPostRefunded         *SuggestedPostRefunded         `json:"suggested_post_refunded,omitempty"`
	VideoChatScheduled            *VideoChatScheduled            `json:"video_chat_scheduled,omitempty"`
	VideoChatStarted              *VideoChatStarted              `json:"video_chat_started,omitempty"`
	VideoChatEnded                *VideoChatEnded                `json:"video_chat_ended,omitempty"`
	VideoChatParticipantsInvited  *VideoChatParticipantsInvited  `json:"video_chat_participants_invited,omitempty"`
	WebAppData                    *WebAppData                    `json:"web_app_data,omitempty"`
}

// MessageAutoDeleteTimerChanged mirrors the object defined by the Telegram Bot API.
type MessageAutoDeleteTimerChanged struct {
	MessageAutoDeleteTime int `json:"message_auto_delete_time"`
}

// MessageEntityBotAPIFields mirrors the object defined by the Telegram Bot API.
type MessageEntityBotAPIFields struct {
	UnixTime       int64  `json:"unix_time,omitempty"`
	DateTimeFormat string `json:"date_time_format,omitempty"`
}

// MessageOriginChannel mirrors the object defined by the Telegram Bot API.
type MessageOriginChannel struct {
	Type            string `json:"type"`
	Date            int64  `json:"date"`
	Chat            Chat   `json:"chat"`
	MessageID       int    `json:"message_id"`
	AuthorSignature string `json:"author_signature,omitempty"`
}

// MessageOriginChat mirrors the object defined by the Telegram Bot API.
type MessageOriginChat struct {
	Type            string `json:"type"`
	Date            int64  `json:"date"`
	SenderChat      Chat   `json:"sender_chat"`
	AuthorSignature string `json:"author_signature,omitempty"`
}

// MessageOriginHiddenUser mirrors the object defined by the Telegram Bot API.
type MessageOriginHiddenUser struct {
	Type           string `json:"type"`
	Date           int64  `json:"date"`
	SenderUserName string `json:"sender_user_name"`
}

// MessageOriginUser mirrors the object defined by the Telegram Bot API.
type MessageOriginUser struct {
	Type       string `json:"type"`
	Date       int64  `json:"date"`
	SenderUser User   `json:"sender_user"`
}

// OwnedGiftRegular mirrors the object defined by the Telegram Bot API.
type OwnedGiftRegular struct {
	Type                    string          `json:"type"`
	Gift                    Gift            `json:"gift"`
	OwnedGiftID             string          `json:"owned_gift_id,omitempty"`
	SenderUser              *User           `json:"sender_user,omitempty"`
	SendDate                int64           `json:"send_date"`
	Text                    string          `json:"text,omitempty"`
	Entities                []MessageEntity `json:"entities,omitempty"`
	IsPrivate               bool            `json:"is_private,omitempty"`
	IsSaved                 bool            `json:"is_saved,omitempty"`
	CanBeUpgraded           bool            `json:"can_be_upgraded,omitempty"`
	WasRefunded             bool            `json:"was_refunded,omitempty"`
	ConvertStarCount        int             `json:"convert_star_count,omitempty"`
	PrepaidUpgradeStarCount int             `json:"prepaid_upgrade_star_count,omitempty"`
	IsUpgradeSeparate       bool            `json:"is_upgrade_separate,omitempty"`
	UniqueGiftNumber        int             `json:"unique_gift_number,omitempty"`
}

// OwnedGiftUnique mirrors the object defined by the Telegram Bot API.
type OwnedGiftUnique struct {
	Type              string     `json:"type"`
	Gift              UniqueGift `json:"gift"`
	OwnedGiftID       string     `json:"owned_gift_id,omitempty"`
	SenderUser        *User      `json:"sender_user,omitempty"`
	SendDate          int64      `json:"send_date"`
	IsSaved           bool       `json:"is_saved,omitempty"`
	CanBeTransferred  bool       `json:"can_be_transferred,omitempty"`
	TransferStarCount int        `json:"transfer_star_count,omitempty"`
	NextTransferDate  int64      `json:"next_transfer_date,omitempty"`
}

// PaidMediaLivePhoto mirrors the object defined by the Telegram Bot API.
type PaidMediaLivePhoto struct {
	Type      string    `json:"type"`
	LivePhoto LivePhoto `json:"live_photo"`
}

// PaidMediaPhoto mirrors the object defined by the Telegram Bot API.
type PaidMediaPhoto struct {
	Type  string      `json:"type"`
	Photo []PhotoSize `json:"photo"`
}

// PaidMediaPreview mirrors the object defined by the Telegram Bot API.
type PaidMediaPreview struct {
	Type     string `json:"type"`
	Width    int    `json:"width,omitempty"`
	Height   int    `json:"height,omitempty"`
	Duration int    `json:"duration,omitempty"`
}

// PaidMediaVideo mirrors the object defined by the Telegram Bot API.
type PaidMediaVideo struct {
	Type  string `json:"type"`
	Video Video  `json:"video"`
}

// PaidMessagePriceChanged mirrors the object defined by the Telegram Bot API.
type PaidMessagePriceChanged struct {
	PaidMessageStarCount int `json:"paid_message_star_count"`
}

// PassportData mirrors the object defined by the Telegram Bot API.
type PassportData struct {
	Data        []EncryptedPassportElement `json:"data"`
	Credentials EncryptedCredentials       `json:"credentials"`
}

// PassportElementErrorDataField mirrors the object defined by the Telegram Bot API.
type PassportElementErrorDataField struct {
	Type      string `json:"type"`
	FieldName string `json:"field_name"`
	DataHash  string `json:"data_hash"`
	Message   string `json:"message"`
}

func (PassportElementErrorDataField) passportElementError() {}

func (PassportElementErrorDataField) PassportElementErrorSource() string { return "data" }

func (value PassportElementErrorDataField) PassportElementErrorType() string { return value.Type }

func (value PassportElementErrorDataField) PassportElementErrorMessage() string { return value.Message }

func (value PassportElementErrorDataField) MarshalJSON() ([]byte, error) {
	type plain PassportElementErrorDataField
	return marshalTagged("source", "data", plain(value))
}

// PassportElementErrorFile mirrors the object defined by the Telegram Bot API.
type PassportElementErrorFile struct {
	Type     string `json:"type"`
	FileHash string `json:"file_hash"`
	Message  string `json:"message"`
}

func (PassportElementErrorFile) passportElementError() {}

func (PassportElementErrorFile) PassportElementErrorSource() string { return "file" }

func (value PassportElementErrorFile) PassportElementErrorType() string { return value.Type }

func (value PassportElementErrorFile) PassportElementErrorMessage() string { return value.Message }

func (value PassportElementErrorFile) MarshalJSON() ([]byte, error) {
	type plain PassportElementErrorFile
	return marshalTagged("source", "file", plain(value))
}

// PassportElementErrorFiles mirrors the object defined by the Telegram Bot API.
type PassportElementErrorFiles struct {
	Type       string   `json:"type"`
	FileHashes []string `json:"file_hashes"`
	Message    string   `json:"message"`
}

func (PassportElementErrorFiles) passportElementError() {}

func (PassportElementErrorFiles) PassportElementErrorSource() string { return "files" }

func (value PassportElementErrorFiles) PassportElementErrorType() string { return value.Type }

func (value PassportElementErrorFiles) PassportElementErrorMessage() string { return value.Message }

func (value PassportElementErrorFiles) MarshalJSON() ([]byte, error) {
	type plain PassportElementErrorFiles
	return marshalTagged("source", "files", plain(value))
}

// PassportElementErrorFrontSide mirrors the object defined by the Telegram Bot API.
type PassportElementErrorFrontSide struct {
	Type     string `json:"type"`
	FileHash string `json:"file_hash"`
	Message  string `json:"message"`
}

func (PassportElementErrorFrontSide) passportElementError() {}

func (PassportElementErrorFrontSide) PassportElementErrorSource() string { return "front_side" }

func (value PassportElementErrorFrontSide) PassportElementErrorType() string { return value.Type }

func (value PassportElementErrorFrontSide) PassportElementErrorMessage() string { return value.Message }

func (value PassportElementErrorFrontSide) MarshalJSON() ([]byte, error) {
	type plain PassportElementErrorFrontSide
	return marshalTagged("source", "front_side", plain(value))
}

// PassportElementErrorReverseSide mirrors the object defined by the Telegram Bot API.
type PassportElementErrorReverseSide struct {
	Type     string `json:"type"`
	FileHash string `json:"file_hash"`
	Message  string `json:"message"`
}

func (PassportElementErrorReverseSide) passportElementError() {}

func (PassportElementErrorReverseSide) PassportElementErrorSource() string { return "reverse_side" }

func (value PassportElementErrorReverseSide) PassportElementErrorType() string { return value.Type }

func (value PassportElementErrorReverseSide) PassportElementErrorMessage() string {
	return value.Message
}

func (value PassportElementErrorReverseSide) MarshalJSON() ([]byte, error) {
	type plain PassportElementErrorReverseSide
	return marshalTagged("source", "reverse_side", plain(value))
}

// PassportElementErrorSelfie mirrors the object defined by the Telegram Bot API.
type PassportElementErrorSelfie struct {
	Type     string `json:"type"`
	FileHash string `json:"file_hash"`
	Message  string `json:"message"`
}

func (PassportElementErrorSelfie) passportElementError() {}

func (PassportElementErrorSelfie) PassportElementErrorSource() string { return "selfie" }

func (value PassportElementErrorSelfie) PassportElementErrorType() string { return value.Type }

func (value PassportElementErrorSelfie) PassportElementErrorMessage() string { return value.Message }

func (value PassportElementErrorSelfie) MarshalJSON() ([]byte, error) {
	type plain PassportElementErrorSelfie
	return marshalTagged("source", "selfie", plain(value))
}

// PassportElementErrorTranslationFile mirrors the object defined by the Telegram Bot API.
type PassportElementErrorTranslationFile struct {
	Type     string `json:"type"`
	FileHash string `json:"file_hash"`
	Message  string `json:"message"`
}

func (PassportElementErrorTranslationFile) passportElementError() {}

func (PassportElementErrorTranslationFile) PassportElementErrorSource() string {
	return "translation_file"
}

func (value PassportElementErrorTranslationFile) PassportElementErrorType() string { return value.Type }

func (value PassportElementErrorTranslationFile) PassportElementErrorMessage() string {
	return value.Message
}

func (value PassportElementErrorTranslationFile) MarshalJSON() ([]byte, error) {
	type plain PassportElementErrorTranslationFile
	return marshalTagged("source", "translation_file", plain(value))
}

// PassportElementErrorTranslationFiles mirrors the object defined by the Telegram Bot API.
type PassportElementErrorTranslationFiles struct {
	Type       string   `json:"type"`
	FileHashes []string `json:"file_hashes"`
	Message    string   `json:"message"`
}

func (PassportElementErrorTranslationFiles) passportElementError() {}

func (PassportElementErrorTranslationFiles) PassportElementErrorSource() string {
	return "translation_files"
}

func (value PassportElementErrorTranslationFiles) PassportElementErrorType() string {
	return value.Type
}

func (value PassportElementErrorTranslationFiles) PassportElementErrorMessage() string {
	return value.Message
}

func (value PassportElementErrorTranslationFiles) MarshalJSON() ([]byte, error) {
	type plain PassportElementErrorTranslationFiles
	return marshalTagged("source", "translation_files", plain(value))
}

// PassportElementErrorUnspecified mirrors the object defined by the Telegram Bot API.
type PassportElementErrorUnspecified struct {
	Type        string `json:"type"`
	ElementHash string `json:"element_hash"`
	Message     string `json:"message"`
}

func (PassportElementErrorUnspecified) passportElementError() {}

func (PassportElementErrorUnspecified) PassportElementErrorSource() string { return "unspecified" }

func (value PassportElementErrorUnspecified) PassportElementErrorType() string { return value.Type }

func (value PassportElementErrorUnspecified) PassportElementErrorMessage() string {
	return value.Message
}

func (value PassportElementErrorUnspecified) MarshalJSON() ([]byte, error) {
	type plain PassportElementErrorUnspecified
	return marshalTagged("source", "unspecified", plain(value))
}

// PassportFile mirrors the object defined by the Telegram Bot API.
type PassportFile struct {
	FileID       string `json:"file_id"`
	FileUniqueID string `json:"file_unique_id"`
	FileSize     int64  `json:"file_size"`
	FileDate     int64  `json:"file_date"`
}

// PollOptionAdded mirrors the object defined by the Telegram Bot API.
type PollOptionAdded struct {
	PollMessage        *MaybeInaccessibleMessage `json:"poll_message,omitempty"`
	OptionPersistentID string                    `json:"option_persistent_id"`
	OptionText         string                    `json:"option_text"`
	OptionTextEntities []MessageEntity           `json:"option_text_entities,omitempty"`
}

// PollOptionDeleted mirrors the object defined by the Telegram Bot API.
type PollOptionDeleted struct {
	PollMessage        *MaybeInaccessibleMessage `json:"poll_message,omitempty"`
	OptionPersistentID string                    `json:"option_persistent_id"`
	OptionText         string                    `json:"option_text"`
	OptionTextEntities []MessageEntity           `json:"option_text_entities,omitempty"`
}

// ProximityAlertTriggered mirrors the object defined by the Telegram Bot API.
type ProximityAlertTriggered struct {
	Traveler User `json:"traveler"`
	Watcher  User `json:"watcher"`
	Distance int  `json:"distance"`
}

// ReactionTypeCustomEmoji mirrors the object defined by the Telegram Bot API.
type ReactionTypeCustomEmoji struct {
	Type          string `json:"type"`
	CustomEmojiID string `json:"custom_emoji_id"`
}

// ReactionTypeEmoji mirrors the object defined by the Telegram Bot API.
type ReactionTypeEmoji struct {
	Type  string `json:"type"`
	Emoji string `json:"emoji"`
}

// ReactionTypePaid mirrors the object defined by the Telegram Bot API.
type ReactionTypePaid struct {
	Type string `json:"type"`
}

// ReplyParametersBotAPIFields mirrors the object defined by the Telegram Bot API.
type ReplyParametersBotAPIFields struct {
	ChecklistTaskID int    `json:"checklist_task_id,omitempty"`
	PollOptionID    string `json:"poll_option_id,omitempty"`
}

// RevenueWithdrawalStateFailed mirrors the object defined by the Telegram Bot API.
type RevenueWithdrawalStateFailed struct {
	Type string `json:"type"`
}

// RevenueWithdrawalStatePending mirrors the object defined by the Telegram Bot API.
type RevenueWithdrawalStatePending struct {
	Type string `json:"type"`
}

// RevenueWithdrawalStateSucceeded mirrors the object defined by the Telegram Bot API.
type RevenueWithdrawalStateSucceeded struct {
	Type string `json:"type"`
	Date int64  `json:"date"`
	URL  string `json:"url"`
}

// RichBlockAnchor mirrors the object defined by the Telegram Bot API.
type RichBlockAnchor struct {
	Type string `json:"type"`
	Name string `json:"name"`
}

// RichBlockAnimation mirrors the object defined by the Telegram Bot API.
type RichBlockAnimation struct {
	Type       string            `json:"type"`
	Animation  Animation         `json:"animation"`
	HasSpoiler bool              `json:"has_spoiler,omitempty"`
	Caption    *RichBlockCaption `json:"caption,omitempty"`
}

// RichBlockAudio mirrors the object defined by the Telegram Bot API.
type RichBlockAudio struct {
	Type    string            `json:"type"`
	Audio   Audio             `json:"audio"`
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// RichBlockBlockQuotation mirrors the object defined by the Telegram Bot API.
type RichBlockBlockQuotation struct {
	Type   string      `json:"type"`
	Blocks []RichBlock `json:"blocks"`
	Credit *RichText   `json:"credit,omitempty"`
}

// RichBlockCollage mirrors the object defined by the Telegram Bot API.
type RichBlockCollage struct {
	Type    string            `json:"type"`
	Blocks  []RichBlock       `json:"blocks"`
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// RichBlockDetails mirrors the object defined by the Telegram Bot API.
type RichBlockDetails struct {
	Type    string      `json:"type"`
	Summary RichText    `json:"summary"`
	Blocks  []RichBlock `json:"blocks"`
	IsOpen  bool        `json:"is_open,omitempty"`
}

// RichBlockDivider mirrors the object defined by the Telegram Bot API.
type RichBlockDivider struct {
	Type string `json:"type"`
}

// RichBlockFooter mirrors the object defined by the Telegram Bot API.
type RichBlockFooter struct {
	Type string   `json:"type"`
	Text RichText `json:"text"`
}

// RichBlockList mirrors the object defined by the Telegram Bot API.
type RichBlockList struct {
	Type  string              `json:"type"`
	Items []RichBlockListItem `json:"items"`
}

// RichBlockListItemBotAPIFields mirrors the object defined by the Telegram Bot API.
type RichBlockListItemBotAPIFields struct {
	Label string `json:"label"`
}

// RichBlockMap mirrors the object defined by the Telegram Bot API.
type RichBlockMap struct {
	Type     string            `json:"type"`
	Location Location          `json:"location"`
	Zoom     int               `json:"zoom"`
	Width    int               `json:"width"`
	Height   int               `json:"height"`
	Caption  *RichBlockCaption `json:"caption,omitempty"`
}

// RichBlockMathematicalExpression mirrors the object defined by the Telegram Bot API.
type RichBlockMathematicalExpression struct {
	Type       string `json:"type"`
	Expression string `json:"expression"`
}

// RichBlockParagraph mirrors the object defined by the Telegram Bot API.
type RichBlockParagraph struct {
	Type string   `json:"type"`
	Text RichText `json:"text"`
}

// RichBlockPhoto mirrors the object defined by the Telegram Bot API.
type RichBlockPhoto struct {
	Type       string            `json:"type"`
	Photo      []PhotoSize       `json:"photo"`
	HasSpoiler bool              `json:"has_spoiler,omitempty"`
	Caption    *RichBlockCaption `json:"caption,omitempty"`
}

// RichBlockPreformatted mirrors the object defined by the Telegram Bot API.
type RichBlockPreformatted struct {
	Type     string   `json:"type"`
	Text     RichText `json:"text"`
	Language string   `json:"language,omitempty"`
}

// RichBlockPullQuotation mirrors the object defined by the Telegram Bot API.
type RichBlockPullQuotation struct {
	Type   string    `json:"type"`
	Text   RichText  `json:"text"`
	Credit *RichText `json:"credit,omitempty"`
}

// RichBlockSectionHeading mirrors the object defined by the Telegram Bot API.
type RichBlockSectionHeading struct {
	Type string   `json:"type"`
	Text RichText `json:"text"`
	Size int      `json:"size"`
}

// RichBlockSlideshow mirrors the object defined by the Telegram Bot API.
type RichBlockSlideshow struct {
	Type    string            `json:"type"`
	Blocks  []RichBlock       `json:"blocks"`
	Caption *RichBlockCaption `json:"caption,omitempty"`
}

// RichBlockTable mirrors the object defined by the Telegram Bot API.
type RichBlockTable struct {
	Type       string                 `json:"type"`
	Cells      [][]RichBlockTableCell `json:"cells"`
	IsBordered bool                   `json:"is_bordered,omitempty"`
	IsStriped  bool                   `json:"is_striped,omitempty"`
	Caption    *RichText              `json:"caption,omitempty"`
}

// RichBlockThinking mirrors the object defined by the Telegram Bot API.
type RichBlockThinking struct {
	Type string   `json:"type"`
	Text RichText `json:"text"`
}

// RichBlockVideo mirrors the object defined by the Telegram Bot API.
type RichBlockVideo struct {
	Type       string            `json:"type"`
	Video      Video             `json:"video"`
	HasSpoiler bool              `json:"has_spoiler,omitempty"`
	Caption    *RichBlockCaption `json:"caption,omitempty"`
}

// RichBlockVoiceNote mirrors the object defined by the Telegram Bot API.
type RichBlockVoiceNote struct {
	Type      string            `json:"type"`
	VoiceNote Voice             `json:"voice_note"`
	Caption   *RichBlockCaption `json:"caption,omitempty"`
}

// SharedUser mirrors the object defined by the Telegram Bot API.
type SharedUser struct {
	UserID    int64       `json:"user_id"`
	FirstName string      `json:"first_name,omitempty"`
	LastName  string      `json:"last_name,omitempty"`
	Username  string      `json:"username,omitempty"`
	Photo     []PhotoSize `json:"photo,omitempty"`
}

// StoryAreaTypeLink mirrors the object defined by the Telegram Bot API.
type StoryAreaTypeLink struct {
	Type string `json:"type"`
	URL  string `json:"url"`
}

// StoryAreaTypeLocation mirrors the object defined by the Telegram Bot API.
type StoryAreaTypeLocation struct {
	Type      string           `json:"type"`
	Latitude  float64          `json:"latitude"`
	Longitude float64          `json:"longitude"`
	Address   *LocationAddress `json:"address,omitempty"`
}

// StoryAreaTypeSuggestedReaction mirrors the object defined by the Telegram Bot API.
type StoryAreaTypeSuggestedReaction struct {
	Type         string       `json:"type"`
	ReactionType ReactionType `json:"reaction_type"`
	IsDark       bool         `json:"is_dark,omitempty"`
	IsFlipped    bool         `json:"is_flipped,omitempty"`
}

// StoryAreaTypeUniqueGift mirrors the object defined by the Telegram Bot API.
type StoryAreaTypeUniqueGift struct {
	Type string `json:"type"`
	Name string `json:"name"`
}

// StoryAreaTypeWeather mirrors the object defined by the Telegram Bot API.
type StoryAreaTypeWeather struct {
	Type            string  `json:"type"`
	Temperature     float64 `json:"temperature"`
	Emoji           string  `json:"emoji"`
	BackgroundColor int     `json:"background_color"`
}

// SuggestedPostApprovalFailed mirrors the object defined by the Telegram Bot API.
type SuggestedPostApprovalFailed struct {
	SuggestedPostMessage *Message           `json:"suggested_post_message,omitempty"`
	Price                SuggestedPostPrice `json:"price"`
}

// SuggestedPostApproved mirrors the object defined by the Telegram Bot API.
type SuggestedPostApproved struct {
	SuggestedPostMessage *Message            `json:"suggested_post_message,omitempty"`
	Price                *SuggestedPostPrice `json:"price,omitempty"`
	SendDate             int64               `json:"send_date"`
}

// SuggestedPostDeclined mirrors the object defined by the Telegram Bot API.
type SuggestedPostDeclined struct {
	SuggestedPostMessage *Message `json:"suggested_post_message,omitempty"`
	Comment              string   `json:"comment,omitempty"`
}

// SuggestedPostInfo mirrors the object defined by the Telegram Bot API.
type SuggestedPostInfo struct {
	State    string              `json:"state"`
	Price    *SuggestedPostPrice `json:"price,omitempty"`
	SendDate int64               `json:"send_date,omitempty"`
}

// SuggestedPostPaid mirrors the object defined by the Telegram Bot API.
type SuggestedPostPaid struct {
	SuggestedPostMessage *Message    `json:"suggested_post_message,omitempty"`
	Currency             string      `json:"currency"`
	Amount               int         `json:"amount,omitempty"`
	StarAmount           *StarAmount `json:"star_amount,omitempty"`
}

// SuggestedPostParameters mirrors the object defined by the Telegram Bot API.
type SuggestedPostParameters struct {
	Price    *SuggestedPostPrice `json:"price,omitempty"`
	SendDate int64               `json:"send_date,omitempty"`
}

// SuggestedPostPrice mirrors the object defined by the Telegram Bot API.
type SuggestedPostPrice struct {
	Currency string `json:"currency"`
	Amount   int    `json:"amount"`
}

// SuggestedPostRefunded mirrors the object defined by the Telegram Bot API.
type SuggestedPostRefunded struct {
	SuggestedPostMessage *Message `json:"suggested_post_message,omitempty"`
	Reason               string   `json:"reason"`
}

// TextQuote mirrors the object defined by the Telegram Bot API.
type TextQuote struct {
	Text     string          `json:"text"`
	Entities []MessageEntity `json:"entities,omitempty"`
	Position int             `json:"position"`
	IsManual bool            `json:"is_manual,omitempty"`
}

// TransactionPartnerAffiliateProgram mirrors the object defined by the Telegram Bot API.
type TransactionPartnerAffiliateProgram struct {
	Type               string `json:"type"`
	SponsorUser        *User  `json:"sponsor_user,omitempty"`
	CommissionPerMille int    `json:"commission_per_mille"`
}

// TransactionPartnerChat mirrors the object defined by the Telegram Bot API.
type TransactionPartnerChat struct {
	Type string `json:"type"`
	Chat Chat   `json:"chat"`
	Gift *Gift  `json:"gift,omitempty"`
}

// TransactionPartnerFragment mirrors the object defined by the Telegram Bot API.
type TransactionPartnerFragment struct {
	Type            string                  `json:"type"`
	WithdrawalState *RevenueWithdrawalState `json:"withdrawal_state,omitempty"`
}

// TransactionPartnerOther mirrors the object defined by the Telegram Bot API.
type TransactionPartnerOther struct {
	Type string `json:"type"`
}

// TransactionPartnerTelegramAds mirrors the object defined by the Telegram Bot API.
type TransactionPartnerTelegramAds struct {
	Type string `json:"type"`
}

// TransactionPartnerTelegramApi mirrors the object defined by the Telegram Bot API.
type TransactionPartnerTelegramApi struct {
	Type         string `json:"type"`
	RequestCount int    `json:"request_count"`
}

// TransactionPartnerUser mirrors the object defined by the Telegram Bot API.
type TransactionPartnerUser struct {
	Type                        string         `json:"type"`
	TransactionType             string         `json:"transaction_type"`
	User                        User           `json:"user"`
	Affiliate                   *AffiliateInfo `json:"affiliate,omitempty"`
	InvoicePayload              string         `json:"invoice_payload,omitempty"`
	SubscriptionPeriod          int            `json:"subscription_period,omitempty"`
	PaidMedia                   []PaidMedia    `json:"paid_media,omitempty"`
	PaidMediaPayload            string         `json:"paid_media_payload,omitempty"`
	Gift                        *Gift          `json:"gift,omitempty"`
	PremiumSubscriptionDuration int            `json:"premium_subscription_duration,omitempty"`
}

// UniqueGiftBackdrop mirrors the object defined by the Telegram Bot API.
type UniqueGiftBackdrop struct {
	Name           string                   `json:"name"`
	Colors         UniqueGiftBackdropColors `json:"colors"`
	RarityPerMille int                      `json:"rarity_per_mille"`
}

// UniqueGiftBackdropColors mirrors the object defined by the Telegram Bot API.
type UniqueGiftBackdropColors struct {
	CenterColor int `json:"center_color"`
	EdgeColor   int `json:"edge_color"`
	SymbolColor int `json:"symbol_color"`
	TextColor   int `json:"text_color"`
}

// UniqueGiftColors mirrors the object defined by the Telegram Bot API.
type UniqueGiftColors struct {
	ModelCustomEmojiID    string `json:"model_custom_emoji_id"`
	SymbolCustomEmojiID   string `json:"symbol_custom_emoji_id"`
	LightThemeMainColor   int    `json:"light_theme_main_color"`
	LightThemeOtherColors []int  `json:"light_theme_other_colors"`
	DarkThemeMainColor    int    `json:"dark_theme_main_color"`
	DarkThemeOtherColors  []int  `json:"dark_theme_other_colors"`
}

// UniqueGiftInfo mirrors the object defined by the Telegram Bot API.
type UniqueGiftInfo struct {
	Gift               UniqueGift `json:"gift"`
	Origin             string     `json:"origin"`
	LastResaleCurrency string     `json:"last_resale_currency,omitempty"`
	LastResaleAmount   int        `json:"last_resale_amount,omitempty"`
	OwnedGiftID        string     `json:"owned_gift_id,omitempty"`
	TransferStarCount  int        `json:"transfer_star_count,omitempty"`
	NextTransferDate   int64      `json:"next_transfer_date,omitempty"`
}

// UniqueGiftModel mirrors the object defined by the Telegram Bot API.
type UniqueGiftModel struct {
	Name           string  `json:"name"`
	Sticker        Sticker `json:"sticker"`
	RarityPerMille int     `json:"rarity_per_mille"`
	Rarity         string  `json:"rarity,omitempty"`
}

// UniqueGiftSymbol mirrors the object defined by the Telegram Bot API.
type UniqueGiftSymbol struct {
	Name           string  `json:"name"`
	Sticker        Sticker `json:"sticker"`
	RarityPerMille int     `json:"rarity_per_mille"`
}

// UserRating mirrors the object defined by the Telegram Bot API.
type UserRating struct {
	Level              int `json:"level"`
	Rating             int `json:"rating"`
	CurrentLevelRating int `json:"current_level_rating"`
	NextLevelRating    int `json:"next_level_rating,omitempty"`
}

// UsersShared mirrors the object defined by the Telegram Bot API.
type UsersShared struct {
	RequestID int          `json:"request_id"`
	Users     []SharedUser `json:"users"`
}

// VideoBotAPIFields mirrors the object defined by the Telegram Bot API.
type VideoBotAPIFields struct {
	Cover          []PhotoSize    `json:"cover,omitempty"`
	StartTimestamp int64          `json:"start_timestamp,omitempty"`
	Qualities      []VideoQuality `json:"qualities,omitempty"`
}

// VideoChatEnded mirrors the object defined by the Telegram Bot API.
type VideoChatEnded struct {
	Duration int `json:"duration"`
}

// VideoChatParticipantsInvited mirrors the object defined by the Telegram Bot API.
type VideoChatParticipantsInvited struct {
	Users []User `json:"users"`
}

// VideoChatScheduled mirrors the object defined by the Telegram Bot API.
type VideoChatScheduled struct {
	StartDate int64 `json:"start_date"`
}

// VideoChatStarted mirrors the object defined by the Telegram Bot API.
type VideoChatStarted struct {
}

// VideoQuality mirrors the object defined by the Telegram Bot API.
type VideoQuality struct {
	FileID       string `json:"file_id"`
	FileUniqueID string `json:"file_unique_id"`
	Width        int    `json:"width"`
	Height       int    `json:"height"`
	Codec        string `json:"codec"`
	FileSize     int64  `json:"file_size,omitempty"`
}

// WebAppData mirrors the object defined by the Telegram Bot API.
type WebAppData struct {
	Data       string `json:"data"`
	ButtonText string `json:"button_text"`
}

// WriteAccessAllowed mirrors the object defined by the Telegram Bot API.
type WriteAccessAllowed struct {
	FromRequest        bool   `json:"from_request,omitempty"`
	WebAppName         string `json:"web_app_name,omitempty"`
	FromAttachmentMenu bool   `json:"from_attachment_menu,omitempty"`
}
