// Command botapi-models generates the factual part of Hermes' Bot API model:
// missing concrete objects and field extensions for hand-maintained structs.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/sidwiskers/hermes/internal/botapi"
)

const (
	generatedName        = "zz_botapi_generated.go"
	generatedAliasesName = "zz_botapi_aliases_generated.go"
)

func main() {
	root := flag.String("root", ".", "Hermes module root")
	specPath := flag.String("spec", "spec/bot-api.json", "checked-in Bot API manifest")
	output := flag.String("output", filepath.Join("types", generatedName), "generated Go file")
	apiOutput := flag.String("api-output", filepath.Join("api", generatedAliasesName), "generated api aliases")
	rootOutput := flag.String("root-output", generatedAliasesName, "generated root aliases")
	flag.Parse()

	schema, err := botapi.Load(filepath.Join(*root, *specPath))
	if err != nil {
		fatal(err)
	}
	inventory, err := botapi.ScanGoWithOptions(*root, botapi.ScanOptions{
		ExcludeFiles: map[string]bool{generatedName: true, generatedAliasesName: true},
	}, "api", "types")
	if err != nil {
		fatal(err)
	}
	report := botapi.Audit(schema, inventory)
	missingTypes := stringSet(report.MissingObjectTypes)
	missingFields := make(map[string]map[string]bool)
	for _, gap := range report.MissingObjectFields {
		if missingFields[gap.Owner] == nil {
			missingFields[gap.Owner] = make(map[string]bool)
		}
		missingFields[gap.Owner][gap.Name] = true
	}

	var source bytes.Buffer
	fmt.Fprintf(&source, "// Code generated by botapi-models from Bot API %s; DO NOT EDIT.\n\n", schema.Version)
	source.WriteString("package types\n\n")
	for _, object := range schema.Objects {
		if missingTypes[object.Name] {
			writeStruct(&source, object.Name, object.Fields)
			if inputMessageContentVariant(object.Name) {
				fmt.Fprintf(&source, "func (%s) inputMessageContent() {}\n\n", object.Name)
			}
			if kind := inlineQueryResultKind(object.Name); kind != "" {
				fmt.Fprintf(&source, "func (%s) inlineQueryResult() {}\n\n", object.Name)
				fmt.Fprintf(&source, "func (%s) InlineQueryResultType() string { return %q }\n\n", object.Name, kind)
				fmt.Fprintf(&source, "func (value %s) InlineQueryResultID() string { return value.ID }\n\n", object.Name)
				fmt.Fprintf(&source, "func (value %s) MarshalJSON() ([]byte, error) {\n", object.Name)
				fmt.Fprintf(&source, "\ttype plain %s\n", object.Name)
				fmt.Fprintf(&source, "\treturn marshalDiscriminated(%q, plain(value))\n", kind)
				source.WriteString("}\n\n")
			}
			if sourceKind := passportElementErrorSource(object.Name); sourceKind != "" {
				fmt.Fprintf(&source, "func (%s) passportElementError() {}\n\n", object.Name)
				fmt.Fprintf(&source, "func (%s) PassportElementErrorSource() string { return %q }\n\n", object.Name, sourceKind)
				fmt.Fprintf(&source, "func (value %s) PassportElementErrorType() string { return value.Type }\n\n", object.Name)
				fmt.Fprintf(&source, "func (value %s) PassportElementErrorMessage() string { return value.Message }\n\n", object.Name)
				fmt.Fprintf(&source, "func (value %s) MarshalJSON() ([]byte, error) {\n", object.Name)
				fmt.Fprintf(&source, "\ttype plain %s\n", object.Name)
				fmt.Fprintf(&source, "\treturn marshalTagged(%q, %q, plain(value))\n", "source", sourceKind)
				source.WriteString("}\n\n")
			}
			continue
		}
		missing := missingFields[object.Name]
		if len(missing) == 0 {
			continue
		}
		fields := make([]botapi.Field, 0, len(missing))
		for _, field := range object.Fields {
			if missing[field.Name] {
				fields = append(fields, field)
			}
		}
		writeStruct(&source, object.Name+"BotAPIFields", fields)
	}

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fatal(fmt.Errorf("format generated models: %w\n%s", err, source.Bytes()))
	}
	if err := writeFile(*root, *output, formatted); err != nil {
		fatal(err)
	}
	if err := writeAliases(*root, schema, "types", "api", "api", "telegram", "github.com/sidwiskers/hermes/types", *apiOutput, false); err != nil {
		fatal(err)
	}
	if err := writeAliases(*root, schema, "api", ".", "hermes", "lowlevel", "github.com/sidwiskers/hermes/api", *rootOutput, true); err != nil {
		fatal(err)
	}
}

func writeAliases(root string, schema botapi.Manifest, sourceDirectory, targetDirectory, packageName, importName, importPath, output string, shallow bool) error {
	source, err := botapi.ScanGo(root, sourceDirectory)
	if err != nil {
		return err
	}
	target, err := botapi.ScanGoWithOptions(root, botapi.ScanOptions{
		ExcludeFiles: map[string]bool{generatedAliasesName: true, filepath.Base(output): true},
		Shallow:      shallow,
	}, targetDirectory)
	if err != nil {
		return err
	}
	names := make([]string, 0, len(schema.Objects)+len(schema.Unions))
	seen := make(map[string]bool)
	appendName := func(name string) {
		key := botapi.NormalizeName(name)
		entry := source.Types[key]
		if seen[key] || entry == nil || len(entry.Names) == 0 || target.Types[key] != nil {
			return
		}
		seen[key] = true
		names = append(names, entry.Names[0])
	}
	for _, object := range schema.Objects {
		appendName(object.Name)
	}
	for _, union := range schema.Unions {
		appendName(union.Name)
	}

	var generated bytes.Buffer
	fmt.Fprintf(&generated, "// Code generated by botapi-models from Bot API %s; DO NOT EDIT.\n\n", schema.Version)
	fmt.Fprintf(&generated, "package %s\n\n", packageName)
	if len(names) != 0 {
		fmt.Fprintf(&generated, "import %s %q\n\n", importName, importPath)
		generated.WriteString("type (\n")
		for _, name := range names {
			fmt.Fprintf(&generated, "\t%s = %s.%s\n", name, importName, name)
		}
		generated.WriteString(")\n")
	}
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		return fmt.Errorf("format generated aliases: %w\n%s", err, generated.Bytes())
	}
	return writeFile(root, output, formatted)
}

func writeFile(root, output string, data []byte) error {
	path := output
	if !filepath.IsAbs(path) {
		path = filepath.Join(root, path)
	}
	return os.WriteFile(path, data, 0o644)
}

func writeStruct(output *bytes.Buffer, name string, fields []botapi.Field) {
	fmt.Fprintf(output, "// %s mirrors the object defined by the Telegram Bot API.\n", name)
	fmt.Fprintf(output, "type %s struct {\n", name)
	for _, field := range fields {
		if field.Name == "type" && inlineQueryResultKind(name) != "" ||
			field.Name == "source" && passportElementErrorSource(name) != "" {
			continue
		}
		tag := field.Name
		if !field.Required {
			tag += ",omitempty"
		}
		fmt.Fprintf(output, "\t%s %s `json:%q`\n", goName(field.Name), goType(field), tag)
	}
	output.WriteString("}\n\n")
}

func passportElementErrorSource(name string) string {
	switch name {
	case "PassportElementErrorDataField":
		return "data"
	case "PassportElementErrorFile":
		return "file"
	case "PassportElementErrorFiles":
		return "files"
	case "PassportElementErrorFrontSide":
		return "front_side"
	case "PassportElementErrorReverseSide":
		return "reverse_side"
	case "PassportElementErrorSelfie":
		return "selfie"
	case "PassportElementErrorTranslationFile":
		return "translation_file"
	case "PassportElementErrorTranslationFiles":
		return "translation_files"
	case "PassportElementErrorUnspecified":
		return "unspecified"
	default:
		return ""
	}
}

func inlineQueryResultKind(name string) string {
	switch name {
	case "InlineQueryResultArticle":
		return "article"
	case "InlineQueryResultAudio", "InlineQueryResultCachedAudio":
		return "audio"
	case "InlineQueryResultCachedDocument", "InlineQueryResultDocument":
		return "document"
	case "InlineQueryResultCachedGif", "InlineQueryResultGif":
		return "gif"
	case "InlineQueryResultCachedMpeg4Gif", "InlineQueryResultMpeg4Gif":
		return "mpeg4_gif"
	case "InlineQueryResultCachedPhoto", "InlineQueryResultPhoto":
		return "photo"
	case "InlineQueryResultCachedSticker":
		return "sticker"
	case "InlineQueryResultCachedVideo", "InlineQueryResultVideo":
		return "video"
	case "InlineQueryResultCachedVoice", "InlineQueryResultVoice":
		return "voice"
	case "InlineQueryResultContact":
		return "contact"
	case "InlineQueryResultGame":
		return "game"
	case "InlineQueryResultLocation":
		return "location"
	case "InlineQueryResultVenue":
		return "venue"
	default:
		return ""
	}
}

func goType(field botapi.Field) string {
	result := baseType(field.Type, field.Name)
	if field.Required || strings.HasPrefix(result, "[]") || result == "any" || result == "InputMessageContent" {
		return result
	}
	switch result {
	case "bool", "float64", "int", "int64", "string":
		return result
	default:
		return "*" + result
	}
}

func baseType(name, fieldName string) string {
	const array = "Array of "
	if strings.HasPrefix(name, array) {
		return "[]" + baseType(strings.TrimPrefix(name, array), fieldName)
	}
	switch name {
	case "Boolean", "True":
		return "bool"
	case "Float", "Float number":
		return "float64"
	case "Integer":
		if fieldName == "date" || strings.HasSuffix(fieldName, "_date") ||
			strings.HasSuffix(fieldName, "_timestamp") || fieldName == "unix_time" ||
			strings.HasSuffix(fieldName, "_user_id") || fieldName == "user_id" ||
			strings.HasSuffix(fieldName, "_chat_id") || fieldName == "chat_id" ||
			strings.HasSuffix(fieldName, "_file_size") || fieldName == "file_size" {
			return "int64"
		}
		return "int"
	case "String":
		return "string"
	default:
		if strings.Contains(name, " or ") || strings.Contains(name, " and ") {
			return "any"
		}
		return name
	}
}

func goName(name string) string {
	initialisms := map[string]string{
		"api": "API", "gif": "GIF", "html": "HTML", "id": "ID", "ids": "IDs",
		"ip": "IP", "json": "JSON", "mime": "MIME", "mpeg4": "MPEG4", "rtl": "RTL",
		"url": "URL", "urls": "URLs", "vcard": "VCard",
	}
	parts := strings.Split(name, "_")
	var result strings.Builder
	for _, part := range parts {
		if replacement := initialisms[part]; replacement != "" {
			result.WriteString(replacement)
			continue
		}
		runes := []rune(part)
		if len(runes) != 0 {
			runes[0] = unicode.ToUpper(runes[0])
		}
		result.WriteString(string(runes))
	}
	return result.String()
}

func inputMessageContentVariant(name string) bool {
	switch name {
	case "InputContactMessageContent", "InputInvoiceMessageContent", "InputLocationMessageContent", "InputTextMessageContent", "InputVenueMessageContent":
		return true
	default:
		return false
	}
}

func stringSet(values []string) map[string]bool {
	result := make(map[string]bool, len(values))
	for _, value := range values {
		result[value] = true
	}
	return result
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
